version: '3'
services:
  # Serveur API Go
  api:
    image: golang:latest
    container_name: go_api
    working_dir: /app
    volumes:
      - ./go:/app
    ports:
      - "8080:8080"
    command: go run .
    depends_on:
      - db
    env_file:
      - env_dev.env
    networks:
      - goinventory_network

  # Front-end React
  frontend:
    image: node:latest
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - api
    networks:
      - goinventory_network

  # Base de données MySQL
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysafepassword
    networks:
      - goinventory_network
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - goinventory_network

  # Service keycloack
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: mysafepassword
    depends_on:
      - db
    volumes:
      - ./keycloack:/opt/jboss/keycloak/standalone/data
    networks:
      - goinventory_network

networks:
  goinventory_network:
    driver: bridge
